# Generated by Django 4.0.3 on 2022-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
    ]
